In [ ]:
#Group Exercise

In [1]:
import numpy as np
import pandas as pd

In [2]:
diabetes_df = pd.read_csv('../week_13/diabetes.csv')
diabetes_df.head(2)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0

1. Write simple (straightforward) definitions for the following parameters for RandomForestClassifier
(https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClass ifier.html) and indicate how they correlate with the precision and recall for the basic diabetes model we built in class. You will need to rerun the model multiple times to do so.


In [3]:
X=diabetes_df.drop('Outcome',axis=1) #Features
y=diabetes_df['Outcome'].values #Target

class sklearn.ensemble.RandomForestClassifier(n_estimators=100, *, criterion='gini', max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features='auto', max_leaf_nodes=None, min_impurity_decrease=0.0, min_impurity_split=None, bootstrap=True, oob_score=False, n_jobs=None, random_state=None, verbose=0, warm_start=False, class_weight=None, ccp_alpha=0.0, max_samples=None)

In [112]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error as MSE
SEED=1
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=SEED)
rfc = RandomForestClassifier(n_estimators=500, min_samples_leaf=0.1, random_state=SEED)
rfc.fit(X_train, y_train)
y_pred = rfc.predict(X_test)
rmse_test = MSE(y_test, y_pred)**(1/2)
print('Test set RMSE of rf: {:.2f}'.format(rmse_test))

Test set RMSE of rf: 0.51


In [113]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[136  10]
 [ 49  36]]
              precision    recall  f1-score   support

           0       0.74      0.93      0.82       146
           1       0.78      0.42      0.55        85

    accuracy                           0.74       231
   macro avg       0.76      0.68      0.69       231
weighted avg       0.75      0.74      0.72       231



In [ ]:
/Parameter                 / Correlation with Precision  /Correlation with Recall /
/-------------------------/------------------------------/------------------------/
|estimators:  precision decreases with increase / recall increases with decrease in estimator
    
|max_depth:  no major or not all any difference in precision and recall with changes
    
|min_samples_split:  There isn't much difference in precision and recall with minimum changes, when min_samples_split increased a lot - precision decreased much compared to decrease in recall

|min_samples_leaf: precision and recall decreased after any number greater than 0.1 and then remained same 
    
|min_weight_fraction_leaf: Gradual decrease in both but precision reduced a lot compared to recall
    
|max_leaf_nodes: no difference in both
    
|min_impurity_decrease: when applied both decreases
    
|min_impurity_split: Both decreased when equal to 1 or greater, from there on remained same.
    

2. How does setting bootstrap=False influence the model performance? Note: the default is bootstrap=True. Explain why your results might be so.

In [15]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
SEED=42
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify=y, random_state=SEED)
dt = DecisionTreeClassifier(max_depth=4, min_samples_leaf=0.16, random_state=SEED)

bc = BaggingClassifier(base_estimator=dt,bootstrap=True, oob_score=True, n_estimators=300, n_jobs=-1)
bc.fit(X_train, y_train)
y_pred = bc.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy of Bagging Classifier: {:.3f}".format(accuracy))
scoreTrue = bc.score(X_test, y_test)
scoreTrue

Accuracy of Bagging Classifier: 0.693


0.6926406926406926

In [16]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[118  32]
 [ 39  42]]
              precision    recall  f1-score   support

           0       0.75      0.79      0.77       150
           1       0.57      0.52      0.54        81

    accuracy                           0.69       231
   macro avg       0.66      0.65      0.66       231
weighted avg       0.69      0.69      0.69       231



In [17]:
#bootstrap - If False, the whole dataset is used to build each tree.
#False - sample training set is always used. 
#True - sample training set is always used with replacement
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
SEED=42
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify=y, random_state=SEED)
dt = DecisionTreeClassifier(max_depth=4, min_samples_leaf=0.16, random_state=SEED)

bc = BaggingClassifier(base_estimator=dt, bootstrap=False, n_estimators=300, n_jobs=-1)
bc.fit(X_train, y_train)
y_pred = bc.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy of Bagging Classifier: {:.3f}".format(accuracy))
scoreFalse = bc.score(X_test, y_test)
scoreFalse
0.6926406926406926

Accuracy of Bagging Classifier: 0.693


0.6926406926406926

In [18]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[118  32]
 [ 39  42]]
              precision    recall  f1-score   support

           0       0.75      0.79      0.77       150
           1       0.57      0.52      0.54        81

    accuracy                           0.69       231
   macro avg       0.66      0.65      0.66       231
weighted avg       0.69      0.69      0.69       231



In [ ]:
# There is no difference when used bootstrap set to True/False, may be because their isn't much variation in the sample data. 