list[0,1,2,3,4,5,6,7,8,9] and reverse the list. 
write a list comprehension to take the reversed list and divide each value by two


In [16]:
list_name= [0,1,2,3,4,5,6,7,8,9]
reversed_list = list_name[::-1]
reversed_list
divided_list = [x/2 for x in reversed_list]
divided_list
#list comprehension useful when we are going to call the function multiple times. 

[4.5, 4.0, 3.5, 3.0, 2.5, 2.0, 1.5, 1.0, 0.5, 0.0]

In [10]:
list_name.reverse()
print(list_name)

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


In [24]:
import numpy as np
v = np.array([[1], [2], [3]])
v2 = np.array([[-1], [-2], [-3]])

In [28]:
v.T

array([[1, 2, 3]])

In [18]:
v.shape

(3, 1)

# Matrices

In [20]:
N = np.array([[1,2,3], [4,5,6], [7,8,9]])
N
#squared matrix - same length and width

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
N.shape

(3, 3)

In [25]:
# scalar - whole number or decima value - effectively a float
x = 3.5
new_matrix = list(zip(v, v2))
# zip - Combined matrices into vectors
new_matrix

[(array([1]), array([-1])),
 (array([2]), array([-2])),
 (array([3]), array([-3]))]

In [ ]:
Dot product - we use dot product to multiple two vectors. IN 2D vectors this is same as matrix multiplication
Produces a scalar value( a number, not a vector) that says the degree to which the two vectors interact. 
Interaction between similar dimensions. 

Why do we care? Ex: solar panel tracking, force diagrams, rendering 

In [27]:
np.dot(v.T, v)

array([[14]])

In [30]:
#can think of this as 1 point on yaxis near the origin
north = np.array([0, 1])
east = np.array([1,0])
#to what degree are north an deast are same? 
np.dot(north, east)

0

In [29]:
#craeate an example for north an dsouth.in other words, find the dot product for north and south. 
north = np.array([0,1])
south = np.array([0, -1])
np.dot(north, south)

-1

In [ ]:
#Cross product. expressed as vector
#type of vector multiplication , but it shows the interaction between different cmponents as exepressed by a 
vector. It tracks all the cross interactions between dimensions
Performing the cross product results in a new vector that is perendicular to both the input 
vectors. 
i=(1,0,0) ||i||=1 i=j*k
j=(0,1,0)

u = v*w = (x1, x2, x3)*(y1, y2, y3)
(x2y3-x3y2)i+

In [34]:
#why do we carae? torque an dmoment of a force
np.cross(v, v2, axisa=0, axisb=0).T

array([[0],
       [0],
       [0]])

In [35]:
v

array([[1],
       [2],
       [3]])

In [36]:
v2

array([[-1],
       [-2],
       [-3]])

In [38]:
#Orthogonality.. two vectors are orthogonal if they are perpendicular to eachother. 
#The dot product is what? 0 or the identity matrix. 
$$ A \cdot A^T=I $$


SyntaxError: invalid syntax (<ipython-input-38-6054b325c126>, line 3)

In [40]:
M = np.array([[1,0,0],
             [0,1,0],
             [0,0,1]])
M
#identity and orthogonal matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [41]:
np.dot(M, N, T)

NameError: name 'T' is not defined

In [ ]:
One Hot Encoding
* A vector represenatation of a categorical value
This is a type of preprocessing used in machine learning. 
So, you are converting categories to numbers so they can be processed better an dmore efficiently
You are creating dummy variables.  