In [5]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]],dtype=np.float32)
print(a)
print(a.ndim, a.shape, a.dtype)

[[1. 2. 3.]
 [4. 5. 6.]]
2 (2, 3) float32


In [11]:
b = np.array([1,2,3,4],ndmin=4)

In [2]:
#practice from Youtube videos
#https://www.youtube.com/watch?v=QUT1VHiLmmI
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b= np.array([[9.0,8.0,7.0], [2.0,3.0,4.0]])
print(b)

[[9. 8. 7.]
 [2. 3. 4.]]


In [7]:
#Get dimension
b.ndim

2

In [8]:
a.ndim

1

In [10]:
#Get Shape
#a.shape  b has 2 rows, 3 coloumns
b.shape

(2, 3)

In [12]:
#Get Type
a.dtype

dtype('int64')

In [21]:
#Get size
#a = np.arrage([1,2,3], dtype='int16') -- this give 2 bytes
a.itemsize
b.itemsize

8

In [19]:
#total number of elements is a.size
#total size
#a.size*a.itemsize
# another way is with number of bites
a.nbytes

24

In [24]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [27]:
#Get a specific element, use a[row,column]
a[1,5]
a[1,-2]

13

In [28]:
#Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [29]:
#Get a specific column
a[: , 3]

array([ 4, 11])

In [30]:
#[startindex: endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [31]:
#replacing with rows and 
columns
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [33]:
##3-dimension
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [34]:
#Get specific element(work outside in)
b[0,1,1]

4

In [35]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [36]:
b[:,1,:] = ([[9,9],[8,8]])
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# Initializing Different Types of Arrays

In [38]:
#All zero matrice
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
#All 1's matrice
np.ones((4,2,2), dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [43]:
#ANy other number ex: 2by 2 matrice with value 99
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [45]:
#Allows to take a shape that is already buit
#np.full_like(a, 4) or 
np.full(a.shape,4)


array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [48]:
#Random decimal number
np.random.rand(4,2,3)

array([[[0.60052543, 0.44613424, 0.02357895],
        [0.88973705, 0.09229814, 0.63926128]],

       [[0.65864771, 0.78753331, 0.93695101],
        [0.3108912 , 0.14265451, 0.31890646]],

       [[0.7066778 , 0.62274752, 0.01424182],
        [0.51150829, 0.24513504, 0.92870938]],

       [[0.74005738, 0.58948687, 0.06019117],
        [0.29672855, 0.36087461, 0.82406216]]])

In [50]:
#Allows to take a shape that is already buit in
#np.full_like(a,4)  or
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [56]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [64]:
#Random INteger values
np.random.randint(4,8, size=(3,3))

array([[5, 7, 6],
       [6, 7, 7],
       [5, 7, 4]])

In [65]:
#Identity Matrix. Default square
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [67]:
output = np.ones((5,5))
print(output)
z = np.zeros((3,3))
z[1,1]=9
print(z)
output[1:-1, 1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


array([180, 215, 210, 210, 188, 176, 209, 200])