### Homework 3 Numpy Arrays

1. Open `cars.csv` in jupyter and look at the data. (Double click `cars.csv` to open in a new tab).
2. We are converting each **column** into an numpy array.
3. Notice we have text, integer and float data. 
4. Take care not to overwrite your starter code.

In [27]:
#Starter code. Do NOT modify this cell
import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])


1. How can you get help on `np.array`?

Call `dir()` on `np.array`. 

Call `dir()` on `car`.

Note the difference. `car` has methods and attributes we can use.

In [28]:
dir(np.array)
dir(car)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

2. What are the numpy datatypes for the `car`,`mpg`, `horsepower` and `origin` arrays? (Hint: Not `type(car)` and use `print()` to print the numpy type.)

In [29]:
print(car.dtype)
print(mpg.dtype)
print(horsepower.dtype)
print(origin.dtype)

object
float64
float64
object


3. `numpy` is often imported as `np`. What is this action called? Why might you do this? 

In [ ]:
numpy is aliasing as np, i.e., numpy can be alternatively called as np. We do this to refer numpy package. 

4. Each of the arrays (cars, mpg, cylinders, etc..) has how many dimensions? Show how to find this using code. 

In [30]:
print(car.ndim)
print(mpg.ndim)
print(cylinders.ndim)

1
1
1


5. Show how to:

- multiply the `mpg` array by 12.
- divide the `mpg` array by 3.
- raise the `mpg` array to the power of 4.
- take the square root of the `mpg` array.

In [31]:
print(mpg*12)
print(mpg/3)
print(np.power(mpg, 4))
print(np.square(mpg))
#print(mpg*mpg) to find square root


[216.  180.  216.  192.  204.  180.  168.  168.  168.  180.    0.    0.
   0.    0.    0.  180.  168.    0.  180.  168.  288.  264.  216.  252.
 324.  312.  300.  288.  300.  312.  252.  120.  120.  132.  108.  324.
 336.  300.  300.    0.  228.  192.  204.  228.  216.  168.  168.  168.
 168.  144.  156.  156.  216.  264.  228.  216.  276.  336.  360.  360.
 372.  420.  324.  312.  288.  300.  276.  240.  252.  156.  168.  180.
 168.  204.  132.  156.  144.  156.  228.  180.  156.  156.  168.  216.
 264.  252.  312.  264.  336.  276.  336.  324.  156.  168.  156.  168.
 180.  144.  156.  156.  168.  156.  144.  156.  216.  192.  216.  216.
 276.  312.  132.  144.  156.  144.  216.  240.  252.  264.  216.  228.
 252.  312.  180.  192.  348.  288.  240.  228.  180.  288.  240.  132.
 240.  252.  228.  180.  372.  312.  384.  300.  192.  192.  216.  192.
 156.  168.  168.  168.  348.  312.  312.  372.  384.  336.  288.  312.
 288.  312.  372.  228.  216.  180.  180.  192.  180.  192.  168

6. What is the ___ of `horsepower`?
- sum
- min
- max
- median
- Optional: mode (May need to google help)

In [32]:
from scipy import stats
print(np.sum(horsepower))
print(np.min(horsepower))
print(np.max(horsepower))
print(np.median(horsepower))
print(stats.mode(horsepower))






42033.0
0.0
230.0
93.5
ModeResult(mode=array([150.]), count=array([22]))


7. Select a subset of `acceleration`. 

- Select only the first 5 elements.
- Select every other element (new selection).

In [33]:
print(acceleration[:6])
print(acceleration[0:-1:2])

[12.  11.5 11.  12.  10.5 10. ]
[12.  11.  10.5  9.  10.  17.5 11.  11.   8.   9.5 15.  15.5 14.5 17.5
 17.5 15.  15.  18.5 15.5 19.  13.  15.5 15.5 11.5 13.  12.  13.5 15.
 14.  19.5 19.  19.  15.5 23.5 16.5 12.  13.  11.  13.5 13.5 14.  14.
 18.  18.  17.  15.  13.  13.  12.5 12.  14.5 11.  16.5 16.  16.  14.
 13.  15.  19.5 13.5 14.  13.  19.5 14.  11.  13.5 16.5 16.  19.  21.
 17.  16.5 14.5 16.  16.5 14.5 19.  15.5 15.  16.  16.  19.5 14.  13.5
 18.5 19.  13.5 16.  16.  13.5 17.  14.  15.  14.5 17.5 16.9 17.7 13.
 13.9 15.4 17.6 22.2 14.2 17.7 16.2 12.2 16.4 15.7 21.9 16.7 12.  14.
 14.8 15.5 12.5 13.7 16.4 17.7 11.1 12.2 14.5 18.2 17.  16.4 14.5 13.5
 14.4 18.6 15.5 12.8 18.2 15.4 17.2 16.7 15.1 13.4 13.7 14.2 14.5 16.7
 14.9 13.6 15.8 16.6 18.2 18.2 15.4 13.2 14.9 15.  14.  14.4 20.1 24.8
 13.2 19.2 16.  12.9 14.7 15.5 16.5 20.1 15.8 17.5 15.2 14.4 21.7 19.9
 13.8 18.  11.4 15.1 17.  16.4 12.6 16.9 16.1 19.4 16.  16.2 14.2 14.4
 14.8 20.4 19.6 13.8 19.  16.6 18.6 16.2 18.  20.5 

8. Show how to select the number `99` in the array below. 

In [34]:
select_99 = np.array([[1,2,3],
                      [4,5,99]])
print(select_99[1,2])

99


9. Select the last element in each subarray (do this with one operation.)

In [35]:
select_more = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
# returns array([3, 6, 9])
print(select_more[:, 2])

[3 6 9]


10. Use the built-in `np.lookfor()` function to search for `'log'`.

Use the function you find and apply it to `mpg`.

In [68]:
np.lookfor('log')
np.sort(mpg)


Search results for 'log'
------------------------
numpy.log
    Natural logarithm, element-wise.
numpy.log2
    Base-2 logarithm of `x`.
numpy.log10
    Return the base 10 logarithm of the input array, element-wise.
numpy.log1p
    Return the natural logarithm of one plus the input array, element-wise.
numpy.logspace
    Return numbers spaced evenly on a log scale.
numpy.logaddexp
    Logarithm of the sum of exponentiations of the inputs.
numpy.logaddexp2
    Logarithm of the sum of exponentiations of the inputs in base-2.
numpy.logical_or
    Compute the truth value of x1 OR x2 element-wise.
numpy.logical_and
    Compute the truth value of x1 AND x2 element-wise.
numpy.logical_not
    Compute the truth value of NOT x element-wise.
numpy.logical_xor
    Compute the truth value of x1 XOR x2, element-wise.
numpy.ma.log
    Natural logarithm, element-wise.
numpy.ma.log2
    Base-2 logarithm of `x`.
numpy.ma.log10
    Return the base 10 logarithm of the input array, element-wise.
numpy.rec

array([ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  9. , 10. , 10. ,
       11. , 11. , 11. , 11. , 12. , 12. , 12. , 12. , 12. , 12. , 13. ,
       13. , 13. , 13. , 13. , 13. , 13. , 13. , 13. , 13. , 13. , 13. ,
       13. , 13. , 13. , 13. , 13. , 13. , 13. , 13. , 14. , 14. , 14. ,
       14. , 14. , 14. , 14. , 14. , 14. , 14. , 14. , 14. , 14. , 14. ,
       14. , 14. , 14. , 14. , 14. , 14.5, 15. , 15. , 15. , 15. , 15. ,
       15. , 15. , 15. , 15. , 15. , 15. , 15. , 15. , 15. , 15. , 15. ,
       15.5, 15.5, 15.5, 15.5, 15.5, 16. , 16. , 16. , 16. , 16. , 16. ,
       16. , 16. , 16. , 16. , 16. , 16. , 16. , 16.2, 16.5, 16.5, 16.5,
       16.9, 17. , 17. , 17. , 17. , 17. , 17. , 17. , 17.5, 17.5, 17.5,
       17.5, 17.5, 17.6, 17.6, 17.7, 18. , 18. , 18. , 18. , 18. , 18. ,
       18. , 18. , 18. , 18. , 18. , 18. , 18. , 18. , 18. , 18. , 18. ,
       18.1, 18.1, 18.2, 18.5, 18.5, 18.5, 18.6, 19. , 19. , 19. , 19. ,
       19. , 19. , 19. , 19. , 19. , 19. , 19. , 19

11. You your google skills to find the unique items in `origin`. (This may not have been covered in the readings.)

In [37]:
np.unique(origin)

array(['Europe', 'Japan', 'US'], dtype=object)

12. 
- Create a 2D array and print its shape as well as ndim. (Any shape is fine)

- Create a 3D array and print its shape as well as ndim.

- Create a 4D array and print its shape as well as ndim. *It's hard to visualize 4-Dimensions but numpy can do it with ease!*

In [38]:
arr1 = np.array([[1,2], [3,4], [5,6]])
print(arr1.shape, arr1.ndim)
arr2 = np.array([[[1,2,3], [4,5,6]], [[3,5,6], [2,2,2]]])
print(arr2.shape, arr2.ndim)
arr3 = np.array([[[[1,2], [3,4]], [[3,3], [4,4]]], [[[2,2], [3,3]], [[4,3], [4,4]]]])
print(arr3.shape, arr3.ndim)




(3, 2) 2
(2, 2, 3) 3
(2, 2, 2, 2) 4


13.Use boolean indexing to create an array of `True/False` using `origin` and the value 'US'.

In [94]:
orgarr =np.array(origin=="US")
orgarr


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True, False, False, False,
       False, False, False,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True, False, False, False, False,  True, False, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
       False, False,  True,  True, False,  True,  True, False, False,
       False, False,

14. Apply your index (from above) to the `car` array. You should now only see cars that are of US origin. 

In [97]:
car[orgarr]
    
    

   
    
        
    
    



array(['Chevrolet Chevelle Malibu', 'Buick Skylark 320',
       'Plymouth Satellite', 'AMC Rebel SST', 'Ford Torino',
       'Ford Galaxie 500', 'Chevrolet Impala', 'Plymouth Fury iii',
       'Pontiac Catalina', 'AMC Ambassador DPL',
       'Chevrolet Chevelle Concours (sw)', 'Ford Torino (sw)',
       'Plymouth Satellite (sw)', 'AMC Rebel SST (sw)',
       'Dodge Challenger SE', "Plymouth 'Cuda 340",
       'Ford Mustang Boss 302', 'Chevrolet Monte Carlo',
       'Buick Estate Wagon (sw)', 'Plymouth Duster', 'AMC Hornet',
       'Ford Maverick', 'AMC Gremlin', 'Ford F250', 'Chevy C20',
       'Dodge D200', 'Hi 1200D', 'Chevrolet Vega 2300', 'Ford Pinto',
       'AMC Gremlin', 'Plymouth Satellite Custom',
       'Chevrolet Chevelle Malibu', 'Ford Torino 500', 'AMC Matador',
       'Chevrolet Impala', 'Pontiac Catalina Brougham',
       'Ford Galaxie 500', 'Plymouth Fury iii', 'Dodge Monaco (sw)',
       'Ford Country Squire (sw)', 'Pontiac Safari (sw)',
       'AMC Hornet Sportabout (

**The remaining questions are OPTIONAL**: The readings did not address all of these so you may have to use some "Google-Fu". 

1.What is an identity matrix? 
Create an identiy matrix of size 5 using an np method. 

In [98]:
Identity matrix is a square matrix with all zeros except the diagonal path. 
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

2. Transpose the following array. 

In [100]:
transpose_me = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
np.transpose(transpose_me)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

3. Why does this multiplication operation fail? 

In [ ]:
arr1 = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
arr2 = np.array([[1,2,3],
                      [4,5,6]])

arr1 * arr2

In [ ]:
arr1 is (3,3) matrix. arr2 is (2,3) matrix. 3columns from arr1 cannot be multiplied with 2 rows from arr2

Use numpy to answer the following questions. 

4. What is the average horsepower for `Europe` cars? (Hint: create boolean index of 'US' apply it to horsepower and perform the calculation.)

In [107]:
Ecars= np.array(origin=='Europe')
Hpower = horsepower[Ecars]
np.mean(Hpower)

78.78082191780823

5. On average are Japanse cars more fuel efficient than US cars? 

In [110]:
Jcars = np.array(origin=='Japan')
JMPG = mpg[Jcars]
np.mean(JMPG)

30.450632911392404

In [111]:
UScars = np.array(origin=='US')
USMPG = mpg[UScars]
np.mean(USMPG)

19.688188976377955

In [ ]:
Yes Japanese cars are 1.5times more fuel efficient that US cars

6. What is the correlation coefficient of `mpg` and `weight`?

In [101]:
np.corrcoef(mpg)
np.corrcoef(weight)

1.0

7. Why might you prefer an `np.array()` over a Python `list`? And when is a Python `list` preferred? 

In [ ]:
Numpy array is faster, uses less bytes of memory, compact i.e., numpy uses contiguous memory. Complex mathematical functions can be performed very easily compared to list.

In [ ]:
Lists can accomodate heterogenous elements, i.e., elements of different data types. whereas numpy is homogeneous and can cause type coercion when different data types are used. 